---
output: html_document
---

# (PART) RATIONALE AND OBJECTIVES  {-}

# The challenge of finding, accessing, and using data {#chapter01}

Many organizations share data online, making numerous and diverse datasets accessible to researchers and analysts. However, a significant challenge arises in practically finding, accessing, and utilizing this wealth of data. Navigating through the vast and continually expanding pool of data sources available online often demands significant time and effort, without a guaranteed identification of datasets that best align with the researcher's needs. Complexities arise from issues such as insufficient metadata, limitations in data discovery tools, and the restricted visibility of valuable data repositories. Addressing technical hurdles related to data discoverability, accessibility, and usability is crucial for improving data sharing policies and optimizing the utility of collected data. The following sections will provide a detailed exploration of these challenges.  

## Finding data


Researchers and data users employ diverse strategies to identify and acquire pre-existing datasets. Some rely on personal networks or academic publications to discover the required data, potentially leading to the use of information that may not align perfectly with the researcher's specific objectives. Alternatively, many data users turn to general search engines or specialized data catalogs in their quest for relevant data resources.

Prominent internet search engines showcase significant capabilities in locating and ranking pertinent online resources. The algorithms behind these search engines integrate both lexical and semantic functionalities. Straightforward data queries, such as searching for *population of India 2023*, yield instant answers (though not always from the most authoritative source). Less specific queries, like searching for *malnutrition in Yemen*, may not provide a direct answer but offer sufficient information and links to useful resources. Generative artificial intelligence has enhanced these search engines' ability to engage with users using natural language, suitable for addressing simple queries, albeit with the potential for errors and inaccuracies. However, internet search engines are not optimized to identify the most relevant data when user requirements cannot be expressed as a straightforward query.

Specialized online data catalogs or data libraries managed by national or international organizations, academic data centers, and data archives offer an alternative for researchers seeking data. However, many of these catalogs employ simple keyword-based search algorithms and often rely on sub-optimal metadata. While they have lexical search capabilities, these are not always adequately optimized, and most lack semantic search capabilities, failing to function as effective recommender systems. With the rapid advancements in technology and the availability of powerful open-source solutions, the search performance of specialized data catalogs can be significantly enhanced, transforming them into effective data recommender systems. This transformation requires not only the adoption of superior technology but also the incorporation of high-quality, comprehensive, and structured metadata. Metadata, providing a detailed description of datasets, is the foundation upon which search engines rely to identify and locate data of interest.

:::quote
Metadata is structured information that describes, explains, locates, or otherwise makes it easier to retrieve, use, or manage an information resource. Metadata is often called data about data or information about information. (National Information Standards Organization, 2004)

Good metadata enables you to understand, use, and share your own data now and in the future and helps other researchers discover, access, use, repurpose, and cite your data in the long term. It also facilitates long-term archival preservation of the data. (Source: [Harvard Medical School](https://datamanagement.hms.harvard.edu/collect-analyze/documentation-metadata))
:::

Metadata are not only needed to enable the data discovery systems. They are also required to allow users to assess the relevance, or fitness-for-purpose, of a dataset. Metadata is the first element that data users examine to assess whether the data align with their requirements. Acquiring a dataset can be time-consuming and occasionally costly activity. Users should be provided with the necessary information to assess the relevance of a dataset prior to acquiring it. 

## Accessing data

Gaining access to data presents a multifaceted challenge that encompasses legal, ethical, and practical considerations. To ensure that data access is not only lawful and ethical but also efficient, fostering relevant and responsible use, both data providers and users must adhere to specific principles and practices:

- **Legal and ethical framework**:
  - Data providers must affirm their legal rights to share the data and articulate clear usage rights for data users.
  - Data users must comprehend how they can employ the data, whether for research, commercial purposes, or other applications, strictly adhering to the specified terms of use.
- **Privacy and ethical standards**:
  - Data access must align with data privacy laws and ethical standards, especially concerning sensitive or personally identifiable information. Handling such data requires utmost care to safeguard individuals' privacy.
- **Comprehensive metadata**:
  - Data providers play a crucial role in furnishing comprehensive metadata that offers context and a thorough understanding of the data. This metadata should encompass details about the data's provenance, including its history, transformations, and processing steps. This understanding is indispensable for accurate and responsible analysis.
- **User-friendly formats**:
  - Data should be made available in user-friendly formats compatible with common data analysis tools, such as CSV, JSON, or Excel.
- **Diverse accessibility**:
  - Data accessibility should cater to various user preferences and capacities. This may involve offering downloadable files, providing access through web-based tools, and supporting data streaming.
  - APIs (Application Programming Interfaces) are crucial for enabling programmable data access. They empower researchers to retrieve and manipulate data programmatically, seamlessly integrating it into their research workflows and applications.

By embracing these principles, the data community can navigate the challenges of accessing data, fostering a framework that ensures legality, ethics, efficiency, and relevance in data usage.

## Using data

The challenge for data users extends beyond merely discovering data; it involves obtaining all the necessary information for a comprehensive understanding of the data and promoting responsible and appropriate use. Take, for instance, a seemingly straightforward indicator label like "unemployment rate (%)"—it may obscure significant variations by country, source, and time. The international recommendations for defining and calculating the "unemployment rate" have evolved, and not all countries utilize the same data collection instrument (e.g., labor force surveys) to gather underlying data. For this reason, detailed metadata should consistently accompany data on online dissemination platforms. This association should be close; relevant metadata ideally should be no more than one click away from the data. This becomes especially crucial when a platform publishes data from multiple sources that aren't fully harmonized.

:::quote
The scope and meaning of labor statistics, in general, are determined by their source and methodology, which holds true for the unemployment rate. To interpret the data accurately, it is crucial to understand what the data convey, how they were collected and constructed, and to have information on the relevant metadata. The design and characteristics of the data source, typically a labor force survey or a similar household survey for the unemployment rate, especially in terms of definitions and concepts used, geographical and age coverage, and reference periods, have significant implications for the resulting data. Taking these aspects into account is essential when analyzing the statistics. Additionally, it is crucial to seek information on any methodological changes and breaks in series to assess their impact on trend analysis and to keep in mind methodological differences across countries when conducting cross-country studies. (From Quick guide on interpreting the unemployment rate, International Labour Office – Geneva: ILO, 2019, ISBN: 978-92-2-133323-4 (web pdf)).
:::

Whenever feasible, reproducible or replicable scripts used with the data, and the analytical output of these scripts, should be published alongside the data. These scripts can be highly valuable to researchers aiming to expand the scope of prior data analysis or reuse portions of the code. They also serve as valuable resources for students seeking to learn from and replicate the work of experienced analysts. In order to enhance data usability, we devised a specific metadata schema tailored for documenting research projects and scripts (see chapter 12). This schema provides a structured framework that contributes to the comprehensive understanding and responsible use of data, fostering transparency and reproducibility in research endeavors.

## A FAIR solution

Improving search capabilities and increasing the accessibility of data requires a combination of enhanced data curation, search engines, and increased accessibility. Adhering to the [FAIR principles (Findable, Accessible, Interoperable, and Reusable)](https://doi.org/10.1371/journal.pcbi.1008469) is an effective approach to data management.

It is essential to focus on the entire data curation process, from acquisition to dissemination, to optimize data analysis by streamlining the process of finding, assessing, accessing, and preparing data. This involves anticipating user needs and investing in data curation for reuse. To ensure data is findable, libraries should implement advanced search algorithms and filters, including full-text, advanced, semantic, and recommendation-based search options. Search engine optimization is also crucial for making catalogs more accessible. Moreover, multiple modes of data access should be available to enhance accessibility, while data should be made interoperable to promote data sharing and reusability. Detailed metadata, including fitness-for-purpose assessments, should be displayed alongside scripts and permanent availability options, such as a DOI, to encourage reuse.
